from django.db import models

class LTE(models.Model):
    layer = models.TextField(default= "brak")
    earfcndl = models.IntegerField()
    dlchbw = models.IntegerField()
    mcc = models.IntegerField()
    mnc = models.IntegerField()
    threshold1 = models.IntegerField()
    enablecovho = models.IntegerField()
    enablebettercellho = models.IntegerField()
    actifho = models.IntegerField()
    a3triggerquantityho = models.IntegerField()
    a3offset = models.IntegerField()
    hysa3offset = models.IntegerField()
    a3timetotrigger = models.IntegerField()
    a3reportinterval = models.IntegerField()
    a5triggerquantityintrafreqho = models.IntegerField()
    threshold3 = models.IntegerField()
    threshold3a = models.IntegerField()
    hysthreshold3 = models.IntegerField()
    a5timetotrigger = models.IntegerField()
    a5reportinterval = models.IntegerField()
    threshold2interfreq = models.IntegerField()
    threshold2a = models.IntegerField()
    a2timetotriggeractinterfreqmeas = models.IntegerField()
    actrsrqinterfreqmobility = models.IntegerField()
    enablecombrsrprsrq = models.IntegerField()
    threshold2mobrsrq = models.IntegerField()
    threshold2arsrq = models.IntegerField()
    a2timetotriggermobrsrq = models.IntegerField()
    a1reportinterval = models.IntegerField()
    threshold2wcdma = models.IntegerField()
    a2timetotriggeractwcdmameas = models.IntegerField()
    eutracarrierinfo = models.IntegerField()
    measquantinterfreq = models.IntegerField()
    a3offsetrsrpinterfreq = models.IntegerField()
    hysa3offsetrsrpinterfreq = models.IntegerField()
    a3offsetrsrqinterfreq = models.IntegerField()
    hysa3offsetrsrqinterfreq = models.IntegerField()
    threshold3interfreq = models.IntegerField()
    threshold3ainterfreq = models.IntegerField()
    hysthreshold3interfreq = models.IntegerField()
    a5timetotriggerinterfreq = models.IntegerField()
    a5reportintervalinterfreq = models.IntegerField()
    threshold3rsrqinterfreq = models.IntegerField()
    threshold3arsrqinterfreq = models.IntegerField()
    hysthreshold3rsrqinterfreq = models.IntegerField()
    a5timetotriggerrsrqinterfreq = models.IntegerField()
    a5reportintervalrsrqinterfreq = models.IntegerField()
    thresholdrsrpiflbfilter = models.IntegerField()
    thresholdrsrpifsbfilter = models.IntegerField()
    threshold3ainterfreqqci1 = models.IntegerField()
    threshold3interfreqqci1 = models.IntegerField()


    def __str__(self):
        return self.layer
